phodal/awesome-iot

README.md

WAMP is an open standard WebSocket subprotocol that provides two application messaging patterns in one unified protocol:
Remote Procedure Calls + Publish & Subscribe.
http://wamp-proto.org/

Add WAMP Message

---

README.md

Added entry for SiteWhere IoT platform. Fixed spelling error in heading.

Added entry for SiteWhere

---

README.md

Add https://github.com/marcgille/thing-it-node/; commercial site: https://www.thing-it.com/
The enclosing `[`... `]` are intended, because they are part of the name

Add [thing-it-node]

---

README.md

awesome-embedded-systems
awesome-embedded-software
awesome-embedded-hardware

add: reference to embedded projects

---

README.md

spelld awesumr

---

README.md

coursera course "Software Architecture for the Internet of Things"

add: course about iot architecture

---

README.md

Fixed typo in the data-visualization area.

Added Thingsboard to list of the Platforms.

---

README.md

Adds our laboratory IoT Platform.

Adds I1820 IoT Platform.

---

README.md

This project is allocated in BitBucket, but it is really curated & userfull. Web GUI is simple, modern but very functional.

Add [ESP8266] Espruna Firmware

---

README.md

add: IIoT platform MindSphere

---

README.md

Adding the Eclipse Foundation IoT top level project and working group page.

Add Eclipse IoT web page

---

README.md

So it turned out issue #41 was more about spaces at the end of the line rather than line endings. Based on git diff I assumed it was mixed line endings. But in the end it was just a few trailing spaces which the Atom editor did automatically fixed up.

Closes #41: Remove trailing whitespaces

---

README.md

Hello,
I was wondering if you would consent to adding Using the Web to Build the IoT to your free books list.
Thanks for your consideration.

adding a free eBook

---

README.md

Provided the Github link to the main repo, where you can get the SD card image.
Signed-off-by: Dieter Reuter <dieter.reuter@me.com>

Add some more details to Hypriot OS

---

README.md

Very nice platform, used them for a couple of projects, lots of integration.

Added Hologram platofrm

---

README.md

Added RMP RTOS into readme

---

README.md

Astarte (https://docs.astarte-platform.org/) is an Open Source IoT platform focused on Data management.
It takes care of everything from collecting data from devices to delivering data to end-user applications. To achieve such a thing, it uses a mixture of mechanisms and paradigm to store organized data, perform live queries.

Add Astarte to Platform

---

README.md

https://github.com/kachkaev/aws-iot-button-logger-to-git/

Add AWS IoT Button logger to git

---

README.md

I sorted the new item alpha :-)

Add t6 as Middleware

---

README.md

Lib:
[Pelion Device Management Client](https://github.com/ARMmbed/mbed-cloud-client) - a library that connects devices to Pelion Device Management service and to Mbed-enabled cloud services from our partners.
Cloud:
[ARM Pelion](https://www.pelion.com/) - "Arm Pelion IoT Platform including Connectivity, Device and Data management service"

Add Arm Pelion cloud and PDMC

---

README.md

Hi, 
I would like to propose this tutorial which I found interesting.
Bests,

Add an mqtt tutorial

---

README.md

Adding .NET Core IoT

---

README.md

Add more awesome blogs to the list

Update blog list

---

README.md

Add Node-RED to home automation list

Update home automation

---

README.md

- stars updated
- forks updated
- accurate description

update t6 IoT

---

README.md

Hi,
Stjepan from manning here. I think this title might be a good match for your list. It's not completely free but has enough free material, and it's part of Manning's early access program. Thank you for considering it.
Best,

Added Edge Computing Technology and Applications

---

README.md

Hi,
added my project in Home Automation.
Hkontroller is SDK library, hkmobile is an application for Android.
Hope it will be merged.

add hkmobile project

---

README.md

- Adding Real-Time Data section (this should be helpful for the newer real-time stuff around now)
- Adding Streamdal to the Real-Time Data section
Streamdal embeds a Wasm-powered workflow engine (sometimes referred to as a data pipeline engine) directly into application code. Incredibly useful for people who specifically need something fast or client-side, on-prem, and local solutions (like for IoT).

Adding Real-Time Data Section and Streamdal

---

README.md

Hi,
Stjepan from Maning here. I've deleted the Edge Computing book that I've added before because the book has been canceled.
Thank you.

Deleted Edge Computing book

---

README.md

Updated link to Moquette MQTT lightweight broker library

Update Moquette link
